baseurl       = "/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "stage"
title = "UBOS - The Linux Distro for Home Servers and Indie IoT Devices"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = [ "miniresp" ]
metaDataFormat = "yaml"
rssLimit = 10

[Params]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true

[Author]
  name = "Indie Computing Corp."

[[menu.main]]
    name = "Getting Started"
    url = "quickstart/"
    weight = 20

[[menu.main]]
    name = "About"
    url = "about/"
    weight = 30

[[menu.main]]
    name = "Apps"
    url = "apps/"
    weight = 40

[[menu.main]]
    name = "Documentation"
    url = "docs/"
    weight = 50

[[menu.main]]
    name = "Press"
    url = "press/"
    weight = 60

[[menu.main]]
    name = "Blog & Videos"
    url = "blog/"
    weight = 70

[[menu.main]]
    name = "Community"
    url = "community/"
    weight = 80
