baseurl       = "/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "UBOS - The Linux Distro for self-hosting your own cloud services"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = []
metaDataFormat = "yaml"
rssLimit = 10

[markup.goldmark.renderer]
    unsafe = true

[Params]
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true

[Author]
  name = "Indie Computing Corp."
